name: getx_mvc_templet
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rename: ^2.0.1
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.7
  shimmer: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  connectivity: ^3.0.6
  intl: ^0.17.0
  get: ^4.6.5
  flutter_native_splash: ^2.2.9
  http: ^0.13.5
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#020447"
  image: assets/images/currency_converter.png
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/images/currency_converter.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#020447"
  adaptive_icon_foreground: "assets/images/currency_converter.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/

